name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        # This assumes your package.json has a "test" script defined.
        # Example: "scripts": { "test": "jest" }
        run: npm test

      - name: Build Docker image
        # Using a fixed tag for demonstration; you can also use a dynamic one.
        run: docker build -t manasa929/nodejs-demo-app:{{ github.sha }} .

      - name: Log in to Docker Hub
        # Corrected syntax with a space after the colon
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: docker push manasa929/nodejs-demo-app:{{ github.sha }}
